#!/usr/bin/perl -si

require "ctime.pl";
require "../lib/sys_config";
require "../lib/forum_config";
if($allow_forum_config){
require "./forum_config";
}
require "../lib/main";
require "../lib/variables";
require "../lib/utilities";


$which_forum = "test";
$script_name = 'a';
$netforum_url = "$base_url/$which_forum/$script_name";

$forum_name = "Test Forum";
$forum_owner = "Administrator";
$forum_owner_code_name = "admin";
$forum_monitor = "NetForum Development Team";
$forum_monitor_email = "netforum-dev\@biostat.wisc.edu";
$forum_monitor_site = "http://www.biostat.wisc.edu/netforum";



if ($ENV{'REQUEST_METHOD'} eq 'GET') {
	&get_url_vars;
	&get_command;
}

if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	&ReadParse();
	&get_url_vars;
	&post_command;
}

