/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class matrix_MatrixF */

#ifndef _Included_matrix_MatrixF
#define _Included_matrix_MatrixF
struct Hexpression_NumExp;

typedef struct Classmatrix_MatrixF {
/* Inaccessible static: nativeCode */
    struct HArrayOfFloat *data;
    long nRows;
    long nCols;
    long nextRow;
    long nextCol;
    long first;
    long last;
    long newRow;
    long newCol;
    long restartRow;
    long restartCol;
    long size;
    long next;
    struct HArrayOfObject *expression;
} Classmatrix_MatrixF;
HandleTo(matrix_MatrixF);

#ifdef __cplusplus
extern "C" {
#endif
extern int64_t matrix_MatrixF_native_version(struct Hmatrix_MatrixF *);
struct Hmatrix_MatrixF;
extern /*boolean*/ long matrix_MatrixF_native_equalEls(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_add1(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_sub(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_subFrom(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_multAdd(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,float,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_addMult(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,float,struct Hmatrix_MatrixF *);
extern float matrix_MatrixF_native_dot(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_replace(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_add2(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,float);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_diag1(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,float);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_diag2(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_mult1(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_mult2(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,float);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_multK(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,float,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_multEl(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_multColMat(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,long,struct Hmatrix_MatrixF *);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_multMatCol(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,long);
extern struct Hmatrix_MatrixF *matrix_MatrixF_native_multDiag(struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *,struct Hmatrix_MatrixF *);
#ifdef __cplusplus
}
#endif
#endif
