/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class matrix_MatrixD */
/* SYMBOL: "matrix_MatrixD/native_version()J", Java_matrix_MatrixD_native_0005fversion_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fversion_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _tval;
	extern int64_t matrix_MatrixD_native_version(void *);
	SET_INT64(_tval, _P_, matrix_MatrixD_native_version(NULL));
	return _P_ + 2;
}
/* SYMBOL: "matrix_MatrixD/native_equalEls(Lmatrix/MatrixD;Lmatrix/MatrixD;)Z", Java_matrix_MatrixD_native_0005fequalEls_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fequalEls_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long matrix_MatrixD_native_equalEls(void *,void *,void *);
	_P_[0].i = (matrix_MatrixD_native_equalEls(NULL,((_P_[0].p)),((_P_[1].p))) ? TRUE : FALSE);
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_add1(Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fadd1_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fadd1_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_add1(void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_add1(NULL,((_P_[0].p)),((_P_[1].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_sub(Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fsub_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fsub_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_sub(void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_sub(NULL,((_P_[0].p)),((_P_[1].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_subFrom(Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fsubFrom_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fsubFrom_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_subFrom(void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_subFrom(NULL,((_P_[0].p)),((_P_[1].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_multAdd(Lmatrix/MatrixD;DLmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmultAdd_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmultAdd_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t1;
	extern void* matrix_MatrixD_native_multAdd(void *,void *,double,void *);
	_P_[0].p = matrix_MatrixD_native_multAdd(NULL,((_P_[0].p)),GET_DOUBLE(_t1, _P_+1),((_P_[3].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_addMult(Lmatrix/MatrixD;DLmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005faddMult_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005faddMult_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t1;
	extern void* matrix_MatrixD_native_addMult(void *,void *,double,void *);
	_P_[0].p = matrix_MatrixD_native_addMult(NULL,((_P_[0].p)),GET_DOUBLE(_t1, _P_+1),((_P_[3].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_dot(Lmatrix/MatrixD;Lmatrix/MatrixD;)D", Java_matrix_MatrixD_native_0005fdot_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fdot_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _tval;
	extern double matrix_MatrixD_native_dot(void *,void *,void *);
	SET_DOUBLE(_tval, _P_, matrix_MatrixD_native_dot(NULL,((_P_[0].p)),((_P_[1].p))));
	return _P_ + 2;
}
/* SYMBOL: "matrix_MatrixD/native_replace(Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005freplace_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005freplace_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_replace(void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_replace(NULL,((_P_[0].p)),((_P_[1].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_add2(Lmatrix/MatrixD;D)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fadd2_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fadd2_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t1;
	extern void* matrix_MatrixD_native_add2(void *,void *,double);
	_P_[0].p = matrix_MatrixD_native_add2(NULL,((_P_[0].p)),GET_DOUBLE(_t1, _P_+1));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_diag1(Lmatrix/MatrixD;D)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fdiag1_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fdiag1_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t1;
	extern void* matrix_MatrixD_native_diag1(void *,void *,double);
	_P_[0].p = matrix_MatrixD_native_diag1(NULL,((_P_[0].p)),GET_DOUBLE(_t1, _P_+1));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_diag2(Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fdiag2_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fdiag2_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_diag2(void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_diag2(NULL,((_P_[0].p)),((_P_[1].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_mult1(Lmatrix/MatrixD;Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmult1_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmult1_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_mult1(void *,void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_mult1(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_mult2(Lmatrix/MatrixD;D)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmult2_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmult2_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t1;
	extern void* matrix_MatrixD_native_mult2(void *,void *,double);
	_P_[0].p = matrix_MatrixD_native_mult2(NULL,((_P_[0].p)),GET_DOUBLE(_t1, _P_+1));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_multK(Lmatrix/MatrixD;DLmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmultK_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmultK_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t1;
	extern void* matrix_MatrixD_native_multK(void *,void *,double,void *);
	_P_[0].p = matrix_MatrixD_native_multK(NULL,((_P_[0].p)),GET_DOUBLE(_t1, _P_+1),((_P_[3].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_multEl(Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmultEl_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmultEl_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_multEl(void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_multEl(NULL,((_P_[0].p)),((_P_[1].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_multColMat(Lmatrix/MatrixD;Lmatrix/MatrixD;ILmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmultColMat_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmultColMat_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_multColMat(void *,void *,void *,long,void *);
	_P_[0].p = matrix_MatrixD_native_multColMat(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].p)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_multMatCol(Lmatrix/MatrixD;Lmatrix/MatrixD;Lmatrix/MatrixD;I)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmultMatCol_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmultMatCol_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_multMatCol(void *,void *,void *,void *,long);
	_P_[0].p = matrix_MatrixD_native_multMatCol(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].p)),((_P_[3].i)));
	return _P_ + 1;
}
/* SYMBOL: "matrix_MatrixD/native_multDiag(Lmatrix/MatrixD;Lmatrix/MatrixD;Lmatrix/MatrixD;)Lmatrix/MatrixD;", Java_matrix_MatrixD_native_0005fmultDiag_stub */
__declspec(dllexport) stack_item *Java_matrix_MatrixD_native_0005fmultDiag_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* matrix_MatrixD_native_multDiag(void *,void *,void *,void *);
	_P_[0].p = matrix_MatrixD_native_multDiag(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].p)));
	return _P_ + 1;
}
