#!/opt/bin/perl -si

# This file contains all of the variables required to run netforum
# You may change any of these but you do so at your own peril.

# $Id: variables,v 1.16 1996/07/31 22:02:31 mcculloh Exp siman $

#########################################################################
#                                                                       #
#      Copyright (c) 1995,96 Board of Regents of the                    #
#      University of Wisconsin System                                   #
#                                                                       #
#                     NetForum 2.0.3                                    #
#  CGI implementation of a Web-based discussion forum system            #
#                                                                       #
#  NetForum Project Team (Past and Present):                            #
#    Roger Caplan                                                       #
#    Mike Dykstra                                                       #
#    Andrew McCulloh                                                    #
#    Jose Siman                                                         #
#  Art by:                                                              #
#    Krista J. Stockebrand                                              #
#    Doreen Maloney                                                     #
#                                                                       #
#         IMPORTANT NOTE: THIS SOFTWARE IS NOT FREE                     #
#                                                                       #
#  You are bound by the terms of the license distributed with the       #
#  NetForum package. The license can also be found at                   #
#     http://www.biostat.wisc.edu/netforum/license.html                 #
#                                                                       #
#                                                                       #
#            IMPORTANT -- AS STATED IN THE LICENSE                      #
#                                                                       #
#  NO MODIFICATIONS TO THE NETFORUM SOFTWARE OR ACCOMPANYING MATERIALS  #
#  INCLUDING DOCUMENATION AND ARTWORK ARE PERMITTED BY ANYONE, WITHOUT  #
#  THE EXPRESSED WRITTEN CONSENT OF THE COPYRIGHT HOLDER.  IN OTHER     #
#  WORDS, DON'T CHANGE THE CODE WITHOUT OUR OK                          #
#                                                                       #
#            IMPORTANT -- AS STATED IN THE LICENSE                      #
#                                                                       #
#  YOU MAY NOT REDISTRIBUTE THE NETFORUM SOFTWARE PACKAGE IN PART OR    #
#  IN WHOLE IN ANY WAY.  IT IS A VIOLATION OF THE LICENSE TO DO SO      #
#                                                                       #
#                                                                       #
#  This program is distributed in the hope that it will be useful,but   #
#  WITHOUT ANY WARRANTY; without even the implied warranty of           #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            #
#                                                                       #
#                                                                       #
#       All documentation can be found at:                              #
#              http://www.biostat.wisc.edu/netforum                     #
#                                                                       #
#                                                                       #
#       Email contact:                                                  #
#              netforum-dev@biostat.wisc.edu                            #
#                                                                       #
#                                                                       #
#       Snail-Mail contact:                                             #
#              NetForum Development Team                                #
#              1300 University Ave, Room 5770                           #
#              Madison, Wi 53706                                        #
#                                                                       #
#########################################################################




# version number 
$v = '2.0.3';

$subject_key = "===subject:";
$separator = "=========yorg=========";
$date_string = "===date:";
$topic_name_key = "===topic_name:";
$poster_site_key = "===psite:";
$poster_name_key = "===from:";
$poster_email_key = "===email:";
$institution_site_key = "===institution_site:";
$poster_institution_key = "===institution:";
$date_key = "===date:";
$formatting_key = "===format:";
$comments_key = "===more:";
$message_key = "===message:";
$empty_topic = "===***empty";
$salt = "JS";

# this is a global command id -- the choice of 4 is an unfortunate feature
# of rodgers code -- it doesnt really matter what it is as long as it
# is unique 
$mail_command = 4;

$show_topics_command = 1;
$add_topic_command = 2;
$show_messages_command = 3;
# mail command = 4 goes here ...
$guidelines_command = 5;	# kill me
$topic_desc_command = 6;	# and me too
$add_message_command = 7;
$show_replies_command = 8;
$add_reply_command = 9;
$edit_reply_command = 10;
$show_group_command = 11;
$show_desc_command = 12;
$format_about_command = 13;
$view_message_expanded = 14;
$expand_messages_command = 15;
$contract_messages_command = 16;
$page_messages_command = 34;	# what happended to 17?
$view_message_contracted = 18;

$edit_topic_command = 1;
$preview_topic_command = 2;
$post_topic_command = 3;
# mail command = 4 goes here ...
$edit_message_command = 5;
$preview_message_command = 6;
$post_message_command = 7;
$preview_reply_command = 8;
$post_reply_command = 9;

# administrative command ids

$create_forum_command = 1;
# $preview_forum_command = 1; moved to end of list
$edit_forum_command = 2;
$post_forum_command = 3;
# mail command = 4 goes here ...
$list_forums_command = 5;
$topic_desc_command = 6;
$post_list_command = 7;
$edit_info_command = 8;
$make_changes_command = 9;
$topic_admin_command = 10;
$post_topic_admin = 11;
$preview_topic_admin = 12;
$edit_message_admin = 13;
$preview_message_update = 14;
$change_message_command = 15;
$delete_message_command = 16;
$view_system_variables = 17;
$edit_system_variables = 18;
$post_system_variables = 19;
$preview_forum_command = 20;
$edit_new_forum_command = 21;
$delete_topic_command = 22;
$delete_forum_command = 23;
$view_forum_variables = 24;
$edit_forum_variables = 25;
$post_forum_variables = 26;
$manage_users_options = 27;
$post_add_user_command = 28;
$post_delete_user_command = 29;
$post_change_user_command = 30;
$post_change_pass_command = 31;
$main_menu_command = 32;
$admin_options_command = 33;
$login_command = 34;
$config_forums_command = 35;
$save_header_command = 36;
$save_footer_command = 37;
$site_config_command = 38;

$cvar_separator = "--";
$mail_separator = "_AT_";

$small_alert_gif = "$docs/gifs/small_alert.gif";


$add_topic_toolbar_gif = "$button_path/add_topic.gif";
$respond_toolbar_gif = "$button_path/respond.gif";
$add_message_toolbar_gif = "$button_path/add_message.gif";
$guidelines_toolbar_gif = "$button_path/guidelines.gif";
$older_toolbar_gif = "$button_path/older.gif";
$newer_toolbar_gif = "$button_path/newer.gif";
$topics_toolbar_gif = "$button_path/topics_list.gif";
$orig_message_toolbar_gif = "$button_path/back.gif";
$next_response_toolbar_gif = "$button_path/next.gif";
$previous_response_toolbar_gif = "$button_path/previous.gif";
$all_responses_toolbar_gif = "$button_path/all.gif";
$email_toolbar_gif = "$button_path/email.gif";
$group_info_toolbar_gif = "$button_path/group_info.gif";
$about_forum_toolbar_gif = "$button_path/about.gif";
$expand_message_toolbar_gif = "$button_path/expand.gif";
$contract_message_toolbar_gif = "$button_path/compress.gif";
$goto_admin_gif = "$button_path/goto_admin.gif";
$goto_login_gif = "$button_path/login.gif";
$help_gif = "$button_path/help.gif";

$change_pass_gif = "$button_path/change_pass.gif";
$create_forum_gif = "$button_path/create_forum.gif";
$edit_forums_gif = "$button_path/edit_forum.gif";
$edit_site_gif = "$button_path/edit_site.gif";
$manage_owners_gif = "$button_path/man_owners.gif";
$list_forums_gif = "$button_path/list_forums.gif";
$back_to_list_gif = "$button_path/list_mess.gif";

$the_year = '1996';		# duh (this is no longer necessary but its
				# a nice little legacy piece of code

# the year will hopefully change to a ctime thing so we dont forget to 
# change it till windows 96 comes out ....


@hot_tamale_tags = ('a', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'dl', 'ol', 'ul', 
'menu', 'dir', 'b>', 'u>', 'i>', 's>', 'b ', 'u ', 'i ', 's ','sub', 'sup', 
'tt', 'pre', 'strong', 'em', 'strike', 'blockquote', 
'samp', 'code', 'var', 'cite', 'dfn', 'address', 'center', 'div', 'table',
'big', 'small', 'kbd', 'font', 'applet', 'map', 'form', 'script' );

1; # Return to sender ...
